// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

#include "route_guide.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace routeguide {
class RouteNoteDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RouteNote>
      _instance;
} _RouteNote_default_instance_;
class ServerInfoReplyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ServerInfoReply>
      _instance;
} _ServerInfoReply_default_instance_;
class ServerInfoRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ServerInfoRequest>
      _instance;
} _ServerInfoRequest_default_instance_;
class LisenceInfoReplyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LisenceInfoReply>
      _instance;
} _LisenceInfoReply_default_instance_;
class LisenceInfoRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LisenceInfoRequest>
      _instance;
} _LisenceInfoRequest_default_instance_;
}  // namespace routeguide
namespace protobuf_route_5fguide_2eproto {
static void InitDefaultsRouteNote() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::routeguide::_RouteNote_default_instance_;
    new (ptr) ::routeguide::RouteNote();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::routeguide::RouteNote::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RouteNote =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRouteNote}, {}};

static void InitDefaultsServerInfoReply() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::routeguide::_ServerInfoReply_default_instance_;
    new (ptr) ::routeguide::ServerInfoReply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::routeguide::ServerInfoReply::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ServerInfoReply =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsServerInfoReply}, {}};

static void InitDefaultsServerInfoRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::routeguide::_ServerInfoRequest_default_instance_;
    new (ptr) ::routeguide::ServerInfoRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::routeguide::ServerInfoRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ServerInfoRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsServerInfoRequest}, {}};

static void InitDefaultsLisenceInfoReply() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::routeguide::_LisenceInfoReply_default_instance_;
    new (ptr) ::routeguide::LisenceInfoReply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::routeguide::LisenceInfoReply::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LisenceInfoReply =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLisenceInfoReply}, {}};

static void InitDefaultsLisenceInfoRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::routeguide::_LisenceInfoRequest_default_instance_;
    new (ptr) ::routeguide::LisenceInfoRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::routeguide::LisenceInfoRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LisenceInfoRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLisenceInfoRequest}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_RouteNote.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ServerInfoReply.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ServerInfoRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LisenceInfoReply.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LisenceInfoRequest.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::RouteNote, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::RouteNote, datasend_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::RouteNote, size_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::ServerInfoReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::ServerInfoReply, revsion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::ServerInfoReply, builddate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::ServerInfoReply, complayname_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::ServerInfoRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::ServerInfoRequest, message_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::LisenceInfoReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::LisenceInfoReply, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::LisenceInfoReply, statues_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::LisenceInfoRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::routeguide::LisenceInfoRequest, clientlicense_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::routeguide::RouteNote)},
  { 7, -1, sizeof(::routeguide::ServerInfoReply)},
  { 15, -1, sizeof(::routeguide::ServerInfoRequest)},
  { 21, -1, sizeof(::routeguide::LisenceInfoReply)},
  { 28, -1, sizeof(::routeguide::LisenceInfoRequest)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::routeguide::_RouteNote_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::routeguide::_ServerInfoReply_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::routeguide::_ServerInfoRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::routeguide::_LisenceInfoReply_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::routeguide::_LisenceInfoRequest_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "route_guide.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021route_guide.proto\022\nrouteguide\"+\n\tRoute"
      "Note\022\020\n\010datasend\030\001 \001(\014\022\014\n\004size\030\002 \001(\005\"J\n\017"
      "ServerInfoReply\022\017\n\007revsion\030\001 \001(\t\022\021\n\tbuil"
      "dDate\030\002 \001(\t\022\023\n\013complayName\030\003 \001(\t\"$\n\021Serv"
      "erInfoRequest\022\017\n\007message\030\001 \001(\t\"4\n\020Lisenc"
      "eInfoReply\022\017\n\007message\030\001 \001(\t\022\017\n\007statues\030\002"
      " \001(\010\"+\n\022LisenceInfoRequest\022\025\n\rclientLice"
      "nse\030\001 \001(\t2\352\001\n\nRouteGuide\022\?\n\tRouteChat\022\025."
      "routeguide.RouteNote\032\025.routeguide.RouteN"
      "ote\"\000(\0010\001\022K\n\013CheckServer\022\035.routeguide.Se"
      "rverInfoRequest\032\033.routeguide.ServerInfoR"
      "eply\"\000\022N\n\014CheckLisence\022\036.routeguide.Lise"
      "nceInfoRequest\032\034.routeguide.LisenceInfoR"
      "eply\"\000B6\n\033io.grpc.examples.routeguideB\017R"
      "outeGuideProtoP\001\242\002\003RTGb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 590);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "route_guide.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_route_5fguide_2eproto
namespace routeguide {

// ===================================================================

void RouteNote::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RouteNote::kDatasendFieldNumber;
const int RouteNote::kSizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RouteNote::RouteNote()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_route_5fguide_2eproto::scc_info_RouteNote.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:routeguide.RouteNote)
}
RouteNote::RouteNote(const RouteNote& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  datasend_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.datasend().size() > 0) {
    datasend_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.datasend_);
  }
  size_ = from.size_;
  // @@protoc_insertion_point(copy_constructor:routeguide.RouteNote)
}

void RouteNote::SharedCtor() {
  datasend_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  size_ = 0;
}

RouteNote::~RouteNote() {
  // @@protoc_insertion_point(destructor:routeguide.RouteNote)
  SharedDtor();
}

void RouteNote::SharedDtor() {
  datasend_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RouteNote::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RouteNote::descriptor() {
  ::protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RouteNote& RouteNote::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_route_5fguide_2eproto::scc_info_RouteNote.base);
  return *internal_default_instance();
}


void RouteNote::Clear() {
// @@protoc_insertion_point(message_clear_start:routeguide.RouteNote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  datasend_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  size_ = 0;
  _internal_metadata_.Clear();
}

bool RouteNote::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:routeguide.RouteNote)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes datasend = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_datasend()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 size = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:routeguide.RouteNote)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:routeguide.RouteNote)
  return false;
#undef DO_
}

void RouteNote::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:routeguide.RouteNote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes datasend = 1;
  if (this->datasend().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->datasend(), output);
  }

  // int32 size = 2;
  if (this->size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:routeguide.RouteNote)
}

::google::protobuf::uint8* RouteNote::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:routeguide.RouteNote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes datasend = 1;
  if (this->datasend().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->datasend(), target);
  }

  // int32 size = 2;
  if (this->size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->size(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:routeguide.RouteNote)
  return target;
}

size_t RouteNote::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:routeguide.RouteNote)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes datasend = 1;
  if (this->datasend().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->datasend());
  }

  // int32 size = 2;
  if (this->size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->size());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RouteNote::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:routeguide.RouteNote)
  GOOGLE_DCHECK_NE(&from, this);
  const RouteNote* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RouteNote>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:routeguide.RouteNote)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:routeguide.RouteNote)
    MergeFrom(*source);
  }
}

void RouteNote::MergeFrom(const RouteNote& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:routeguide.RouteNote)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.datasend().size() > 0) {

    datasend_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.datasend_);
  }
  if (from.size() != 0) {
    set_size(from.size());
  }
}

void RouteNote::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:routeguide.RouteNote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RouteNote::CopyFrom(const RouteNote& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:routeguide.RouteNote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RouteNote::IsInitialized() const {
  return true;
}

void RouteNote::Swap(RouteNote* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RouteNote::InternalSwap(RouteNote* other) {
  using std::swap;
  datasend_.Swap(&other->datasend_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(size_, other->size_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RouteNote::GetMetadata() const {
  protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ServerInfoReply::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ServerInfoReply::kRevsionFieldNumber;
const int ServerInfoReply::kBuildDateFieldNumber;
const int ServerInfoReply::kComplayNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ServerInfoReply::ServerInfoReply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_route_5fguide_2eproto::scc_info_ServerInfoReply.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:routeguide.ServerInfoReply)
}
ServerInfoReply::ServerInfoReply(const ServerInfoReply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  revsion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.revsion().size() > 0) {
    revsion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.revsion_);
  }
  builddate_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.builddate().size() > 0) {
    builddate_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.builddate_);
  }
  complayname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.complayname().size() > 0) {
    complayname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.complayname_);
  }
  // @@protoc_insertion_point(copy_constructor:routeguide.ServerInfoReply)
}

void ServerInfoReply::SharedCtor() {
  revsion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  builddate_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  complayname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ServerInfoReply::~ServerInfoReply() {
  // @@protoc_insertion_point(destructor:routeguide.ServerInfoReply)
  SharedDtor();
}

void ServerInfoReply::SharedDtor() {
  revsion_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  builddate_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  complayname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ServerInfoReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ServerInfoReply::descriptor() {
  ::protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ServerInfoReply& ServerInfoReply::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_route_5fguide_2eproto::scc_info_ServerInfoReply.base);
  return *internal_default_instance();
}


void ServerInfoReply::Clear() {
// @@protoc_insertion_point(message_clear_start:routeguide.ServerInfoReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  revsion_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  builddate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  complayname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ServerInfoReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:routeguide.ServerInfoReply)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string revsion = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_revsion()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->revsion().data(), static_cast<int>(this->revsion().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "routeguide.ServerInfoReply.revsion"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string buildDate = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_builddate()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->builddate().data(), static_cast<int>(this->builddate().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "routeguide.ServerInfoReply.buildDate"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string complayName = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_complayname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->complayname().data(), static_cast<int>(this->complayname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "routeguide.ServerInfoReply.complayName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:routeguide.ServerInfoReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:routeguide.ServerInfoReply)
  return false;
#undef DO_
}

void ServerInfoReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:routeguide.ServerInfoReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string revsion = 1;
  if (this->revsion().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->revsion().data(), static_cast<int>(this->revsion().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.ServerInfoReply.revsion");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->revsion(), output);
  }

  // string buildDate = 2;
  if (this->builddate().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->builddate().data(), static_cast<int>(this->builddate().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.ServerInfoReply.buildDate");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->builddate(), output);
  }

  // string complayName = 3;
  if (this->complayname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->complayname().data(), static_cast<int>(this->complayname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.ServerInfoReply.complayName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->complayname(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:routeguide.ServerInfoReply)
}

::google::protobuf::uint8* ServerInfoReply::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:routeguide.ServerInfoReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string revsion = 1;
  if (this->revsion().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->revsion().data(), static_cast<int>(this->revsion().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.ServerInfoReply.revsion");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->revsion(), target);
  }

  // string buildDate = 2;
  if (this->builddate().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->builddate().data(), static_cast<int>(this->builddate().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.ServerInfoReply.buildDate");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->builddate(), target);
  }

  // string complayName = 3;
  if (this->complayname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->complayname().data(), static_cast<int>(this->complayname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.ServerInfoReply.complayName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->complayname(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:routeguide.ServerInfoReply)
  return target;
}

size_t ServerInfoReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:routeguide.ServerInfoReply)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string revsion = 1;
  if (this->revsion().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->revsion());
  }

  // string buildDate = 2;
  if (this->builddate().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->builddate());
  }

  // string complayName = 3;
  if (this->complayname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->complayname());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ServerInfoReply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:routeguide.ServerInfoReply)
  GOOGLE_DCHECK_NE(&from, this);
  const ServerInfoReply* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ServerInfoReply>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:routeguide.ServerInfoReply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:routeguide.ServerInfoReply)
    MergeFrom(*source);
  }
}

void ServerInfoReply::MergeFrom(const ServerInfoReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:routeguide.ServerInfoReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.revsion().size() > 0) {

    revsion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.revsion_);
  }
  if (from.builddate().size() > 0) {

    builddate_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.builddate_);
  }
  if (from.complayname().size() > 0) {

    complayname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.complayname_);
  }
}

void ServerInfoReply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:routeguide.ServerInfoReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServerInfoReply::CopyFrom(const ServerInfoReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:routeguide.ServerInfoReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerInfoReply::IsInitialized() const {
  return true;
}

void ServerInfoReply::Swap(ServerInfoReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ServerInfoReply::InternalSwap(ServerInfoReply* other) {
  using std::swap;
  revsion_.Swap(&other->revsion_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  builddate_.Swap(&other->builddate_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  complayname_.Swap(&other->complayname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ServerInfoReply::GetMetadata() const {
  protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ServerInfoRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ServerInfoRequest::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ServerInfoRequest::ServerInfoRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_route_5fguide_2eproto::scc_info_ServerInfoRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:routeguide.ServerInfoRequest)
}
ServerInfoRequest::ServerInfoRequest(const ServerInfoRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  // @@protoc_insertion_point(copy_constructor:routeguide.ServerInfoRequest)
}

void ServerInfoRequest::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ServerInfoRequest::~ServerInfoRequest() {
  // @@protoc_insertion_point(destructor:routeguide.ServerInfoRequest)
  SharedDtor();
}

void ServerInfoRequest::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ServerInfoRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ServerInfoRequest::descriptor() {
  ::protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ServerInfoRequest& ServerInfoRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_route_5fguide_2eproto::scc_info_ServerInfoRequest.base);
  return *internal_default_instance();
}


void ServerInfoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:routeguide.ServerInfoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ServerInfoRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:routeguide.ServerInfoRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string message = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "routeguide.ServerInfoRequest.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:routeguide.ServerInfoRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:routeguide.ServerInfoRequest)
  return false;
#undef DO_
}

void ServerInfoRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:routeguide.ServerInfoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.ServerInfoRequest.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->message(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:routeguide.ServerInfoRequest)
}

::google::protobuf::uint8* ServerInfoRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:routeguide.ServerInfoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.ServerInfoRequest.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:routeguide.ServerInfoRequest)
  return target;
}

size_t ServerInfoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:routeguide.ServerInfoRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string message = 1;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ServerInfoRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:routeguide.ServerInfoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ServerInfoRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ServerInfoRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:routeguide.ServerInfoRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:routeguide.ServerInfoRequest)
    MergeFrom(*source);
  }
}

void ServerInfoRequest::MergeFrom(const ServerInfoRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:routeguide.ServerInfoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
}

void ServerInfoRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:routeguide.ServerInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServerInfoRequest::CopyFrom(const ServerInfoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:routeguide.ServerInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerInfoRequest::IsInitialized() const {
  return true;
}

void ServerInfoRequest::Swap(ServerInfoRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ServerInfoRequest::InternalSwap(ServerInfoRequest* other) {
  using std::swap;
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ServerInfoRequest::GetMetadata() const {
  protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void LisenceInfoReply::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LisenceInfoReply::kMessageFieldNumber;
const int LisenceInfoReply::kStatuesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LisenceInfoReply::LisenceInfoReply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_route_5fguide_2eproto::scc_info_LisenceInfoReply.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:routeguide.LisenceInfoReply)
}
LisenceInfoReply::LisenceInfoReply(const LisenceInfoReply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  statues_ = from.statues_;
  // @@protoc_insertion_point(copy_constructor:routeguide.LisenceInfoReply)
}

void LisenceInfoReply::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  statues_ = false;
}

LisenceInfoReply::~LisenceInfoReply() {
  // @@protoc_insertion_point(destructor:routeguide.LisenceInfoReply)
  SharedDtor();
}

void LisenceInfoReply::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LisenceInfoReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LisenceInfoReply::descriptor() {
  ::protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LisenceInfoReply& LisenceInfoReply::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_route_5fguide_2eproto::scc_info_LisenceInfoReply.base);
  return *internal_default_instance();
}


void LisenceInfoReply::Clear() {
// @@protoc_insertion_point(message_clear_start:routeguide.LisenceInfoReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  statues_ = false;
  _internal_metadata_.Clear();
}

bool LisenceInfoReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:routeguide.LisenceInfoReply)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string message = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "routeguide.LisenceInfoReply.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool statues = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &statues_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:routeguide.LisenceInfoReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:routeguide.LisenceInfoReply)
  return false;
#undef DO_
}

void LisenceInfoReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:routeguide.LisenceInfoReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.LisenceInfoReply.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->message(), output);
  }

  // bool statues = 2;
  if (this->statues() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->statues(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:routeguide.LisenceInfoReply)
}

::google::protobuf::uint8* LisenceInfoReply::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:routeguide.LisenceInfoReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.LisenceInfoReply.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message(), target);
  }

  // bool statues = 2;
  if (this->statues() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->statues(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:routeguide.LisenceInfoReply)
  return target;
}

size_t LisenceInfoReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:routeguide.LisenceInfoReply)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string message = 1;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // bool statues = 2;
  if (this->statues() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LisenceInfoReply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:routeguide.LisenceInfoReply)
  GOOGLE_DCHECK_NE(&from, this);
  const LisenceInfoReply* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LisenceInfoReply>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:routeguide.LisenceInfoReply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:routeguide.LisenceInfoReply)
    MergeFrom(*source);
  }
}

void LisenceInfoReply::MergeFrom(const LisenceInfoReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:routeguide.LisenceInfoReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.statues() != 0) {
    set_statues(from.statues());
  }
}

void LisenceInfoReply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:routeguide.LisenceInfoReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LisenceInfoReply::CopyFrom(const LisenceInfoReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:routeguide.LisenceInfoReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LisenceInfoReply::IsInitialized() const {
  return true;
}

void LisenceInfoReply::Swap(LisenceInfoReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LisenceInfoReply::InternalSwap(LisenceInfoReply* other) {
  using std::swap;
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(statues_, other->statues_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LisenceInfoReply::GetMetadata() const {
  protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void LisenceInfoRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LisenceInfoRequest::kClientLicenseFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LisenceInfoRequest::LisenceInfoRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_route_5fguide_2eproto::scc_info_LisenceInfoRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:routeguide.LisenceInfoRequest)
}
LisenceInfoRequest::LisenceInfoRequest(const LisenceInfoRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clientlicense_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.clientlicense().size() > 0) {
    clientlicense_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.clientlicense_);
  }
  // @@protoc_insertion_point(copy_constructor:routeguide.LisenceInfoRequest)
}

void LisenceInfoRequest::SharedCtor() {
  clientlicense_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

LisenceInfoRequest::~LisenceInfoRequest() {
  // @@protoc_insertion_point(destructor:routeguide.LisenceInfoRequest)
  SharedDtor();
}

void LisenceInfoRequest::SharedDtor() {
  clientlicense_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LisenceInfoRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LisenceInfoRequest::descriptor() {
  ::protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LisenceInfoRequest& LisenceInfoRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_route_5fguide_2eproto::scc_info_LisenceInfoRequest.base);
  return *internal_default_instance();
}


void LisenceInfoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:routeguide.LisenceInfoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clientlicense_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool LisenceInfoRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:routeguide.LisenceInfoRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string clientLicense = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_clientlicense()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->clientlicense().data(), static_cast<int>(this->clientlicense().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "routeguide.LisenceInfoRequest.clientLicense"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:routeguide.LisenceInfoRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:routeguide.LisenceInfoRequest)
  return false;
#undef DO_
}

void LisenceInfoRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:routeguide.LisenceInfoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string clientLicense = 1;
  if (this->clientlicense().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->clientlicense().data(), static_cast<int>(this->clientlicense().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.LisenceInfoRequest.clientLicense");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->clientlicense(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:routeguide.LisenceInfoRequest)
}

::google::protobuf::uint8* LisenceInfoRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:routeguide.LisenceInfoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string clientLicense = 1;
  if (this->clientlicense().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->clientlicense().data(), static_cast<int>(this->clientlicense().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "routeguide.LisenceInfoRequest.clientLicense");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->clientlicense(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:routeguide.LisenceInfoRequest)
  return target;
}

size_t LisenceInfoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:routeguide.LisenceInfoRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string clientLicense = 1;
  if (this->clientlicense().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->clientlicense());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LisenceInfoRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:routeguide.LisenceInfoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const LisenceInfoRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LisenceInfoRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:routeguide.LisenceInfoRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:routeguide.LisenceInfoRequest)
    MergeFrom(*source);
  }
}

void LisenceInfoRequest::MergeFrom(const LisenceInfoRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:routeguide.LisenceInfoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.clientlicense().size() > 0) {

    clientlicense_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.clientlicense_);
  }
}

void LisenceInfoRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:routeguide.LisenceInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LisenceInfoRequest::CopyFrom(const LisenceInfoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:routeguide.LisenceInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LisenceInfoRequest::IsInitialized() const {
  return true;
}

void LisenceInfoRequest::Swap(LisenceInfoRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LisenceInfoRequest::InternalSwap(LisenceInfoRequest* other) {
  using std::swap;
  clientlicense_.Swap(&other->clientlicense_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LisenceInfoRequest::GetMetadata() const {
  protobuf_route_5fguide_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_route_5fguide_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace routeguide
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::routeguide::RouteNote* Arena::CreateMaybeMessage< ::routeguide::RouteNote >(Arena* arena) {
  return Arena::CreateInternal< ::routeguide::RouteNote >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::routeguide::ServerInfoReply* Arena::CreateMaybeMessage< ::routeguide::ServerInfoReply >(Arena* arena) {
  return Arena::CreateInternal< ::routeguide::ServerInfoReply >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::routeguide::ServerInfoRequest* Arena::CreateMaybeMessage< ::routeguide::ServerInfoRequest >(Arena* arena) {
  return Arena::CreateInternal< ::routeguide::ServerInfoRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::routeguide::LisenceInfoReply* Arena::CreateMaybeMessage< ::routeguide::LisenceInfoReply >(Arena* arena) {
  return Arena::CreateInternal< ::routeguide::LisenceInfoReply >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::routeguide::LisenceInfoRequest* Arena::CreateMaybeMessage< ::routeguide::LisenceInfoRequest >(Arena* arena) {
  return Arena::CreateInternal< ::routeguide::LisenceInfoRequest >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
